---
title: "Capstone Survey Analysis"
author: "William Baker-Robinson and Kevin Ng"
date: "3/7/2020"
output: html_document
params:
  availSurv: NA
  projSurv: NA
  eligible: NA
  projInfo: NA
  host: NA
  dbName: NA
  username: NA
  password: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r param vars for python}
host <- params$host
dbName <- params$dbName
username <- params$username
password <- params$password
```

```{python connect to database}
import psycopg2
import pandas

connected = True
dbData = False

try:
    conn = psycopg2.connect(
      dbname = r.dbName,
      user = r.username,
      host = r.host,
      password = r.password
    )
except:
    print("Unable to connect to database")
    connected = False
if(connected):
    cur = conn.cursor()
# CHECK IF STUDENT HAS DATA IN IT
if(student == True)
  dbData = True
```

```{r check user uploads and clean}
#check to see if the user uploaded any docs
userData <- FALSE
availSurv <- FALSE
projSurv <- FALSE
eligible <- FALSE
projInfo <- FALSE
if(py$connected == TRUE){
  # check avail surv
    # if true clean
    # set to true
  # check proj surv
    # if true clean
    # set to true
  # check eligible
    # if true clean
    # set to true
  # check projInfo
    # if true clean
    # set to true
  userData <- TRUE
}
```

```{python update or upload}
canQuery = False

if (connected == True and r.userData == True and dbData == False):
  # run ddl 
  # upload all...
  canQuery = True
# elif (connected == True and r.userData == True and dbData == True):
  #Will create if have time
    #find where new data starts in student avail
    #assumption is that only the survey 1 & 2 data will be uploaded and updated like this
    #compare new section to prev to check for duplicate stu id
    # keep track of all id which are duplicated
    # update info for duplicated
    # load the rest to DB
  #canQuery = True
elif (connected == True and r.userData == False and dbData == True):
  canQuery = True  
else:
  print("Not connected")
```

```{python}
if(connected):
  conn.close()
```

